environment:
  name: Prod
  identifier: Prod
  tags:
    custom-plugins: ""
  type: Production
  orgIdentifier: ${HARNESS_ORG}
  projectIdentifier: ${HARNESS_PROJECT}
  variables:
    - name: column_id
      type: String
      description: Kanboard column id this environment maps to
      value: "${KANBOARD_COL_PROD}"
