apiVersion: v1
kind: Service
metadata:
  name: custom-plugins-demo
  labels:
    app: custom-plugins-demo
spec:
  type: ClusterIP
  selector:
    app: custom-plugins-demo
  ports:
    - port: 80
      targetPort: 8080
